import Header from '@/components/header/Header'
import type { Metadata } from 'next'
import { Geist_Mono } from 'next/font/google'
import '../styles/globals.scss'

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Mathify',
	description: 'Generated by create next app',
	icons: '/logo.webp',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${geistMono.variable}`}>
				<Header />
				{children}
			</body>
		</html>
	)
}
