import Footer from '@/components/footer/Footer'
import Header from '@/components/header/Header'
import ReduxProvider from '@/components/redux-provider/ReduxProvider'
import type { Metadata } from 'next'
import { Geist_Mono } from 'next/font/google'
import '../styles/globals.scss'

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Mathify',
	description: 'Generated by create next app',
	icons: '/logo.webp',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${geistMono.variable}`}>
				<ReduxProvider>
					<Header />
					{children}
					<Footer />
				</ReduxProvider>
			</body>
		</html>
	)
}
